<?php

/**
 * TblAdmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class TblAdmin extends BaseTblAdmin
{
  public function get_user_by_login($username, $password)
	{
		$query = Doctrine_Query::create()
			->select("a.*")
			->from("TblAdmin a")
			->where("a.username = :username AND a.password = :password",
				array(
						":username" => $username,
						":password" => $password
				));

		$result = $query->execute();
		
		if(count($result) > 0) 
		{
		  $result = $result->getFirst();
			$result->logins ++;
			$result->last_login = strtotime("now");
			$result->save();
			
			return $result;
		}
		else 
		{
		  return null;
		}
	}
}