<?php

/**
 * TblAnswers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class TblAnswers extends BaseTblAnswers
{
  public function get_user_answer($user_id)
	{
	  $query = Doctrine_Query::create()
		  ->from("TblAnswers a")
			->where("a.user_id = ?", $user_id);
			
		return $query->execute();
	}
	
	public function get_answer_by_question($user_id, $question_id)
	{
	  $query = Doctrine_Query::create()
			->from("TblAnswers a")
			->where("a.user_id = ?", $user_id)
			->andWhere("a.q_id = ?", $question_id)
			->orderBy("a.date_created DESC");
			
		return $query;
	}
}