<?php

/**
 * TblUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class TblUsers extends BaseTblUsers
{
  public function get_user_by_code($code)
	{
	  $query = Doctrine_Query::create()
			->select("u.*")
			->from("TblUsers u")
			->where("u.code = ?", $code);
			
	  $result = $query->execute();
		
		if(count($result) > 0) 
		{
		  $result = $result->getFirst();
			$result->logins ++;
			$result->last_login = strtotime("now");
			$result->save();
			
			return $result;
		}
		else 
		{
		  return null;
		}
	}
	
	public function search_user($keyword, $choice)
	{
	  $query = Doctrine_Query::create()
			->select("u.*")
			->from("TblUsers u");
			
		if ($keyword != null && $choice == 'name')
		{
			$query->where(
				"(".
				"u.first_name LIKE :key OR " .
				"u.last_name LIKE :key" .
				")", array(
				":key" => "%$keyword%"));
		}
		else if ($keyword != null && $choice == 'company')
		{
			$query->where(
				"(".
				"u.company LIKE :key " .
				")", array(
				":key" => "%$keyword%"));
		}	
		else if ($keyword != null && $choice == 'position')
		{
			$query->where(
				"(".
				"u.position LIKE :key " .
				")", array(
				":key" => "%$keyword%"));
		}
		else if ($keyword != null && $choice == 'status')
		{
			$query->where(
				"(".
				"u.status LIKE :key " .
				")", array(
				":key" => "$keyword%"));
		}
		
		return $query->execute();
	}
}