<?php

/**
 * Tblimages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Tblimages extends BaseTblimages
{
  public function getSql()
  {
    $query = Doctrine_Query::create()
        ->select("i.*")
        ->from("Tblimages i");

    $result = $query->execute();
    return $query;
  }

  public function search($keyword, $page, $status)
  {
    $limit = 30;

    if($page < 1)
      $offset = 0;
    else
      $offset = ($page - 1) * $limit;

    $query = Doctrine_Query::create()
      ->from("Tblimages i")
      ->where("i.status = ?", $status)
      ->limit($limit)
      ->offset($offset);

    return $query;
  }

  public function list_of_images($keyword, $page)
  {
    $limit = 33;

    if($page < 1)
      $offset = 0;
    else
      $offset = ($page - 1) * $limit;

    $query = Doctrine_Query::create()
      ->from("Tblimages i")
      ->limit($limit)
      ->offset($offset);

    return $query;
  }
}